import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body >
      
      <header className="bg-gray-800 text-white p-4 text-center">
              We will be releasing version 1.1.0 soon...
            </header>
      
      {children}
      
      <footer className="bg-gray-800 text-white text-center p-4 mt-8">
              © 2025 Sari App | MountainKid AI
            </footer>
      </body>
    </html>
  );
}
